Main:
  Automatic Tree Destruction: true
  Use Permissions: false
  Sapling Replant: true
  Apply Full Tool Damage: true
  Ignore User Placed Blocks: false
  Use mcMMO if Available: true
  Destroy Only Blocks Above: false
Automatic Tree Destruction:
  Tree Types:
    Birch: true
    Jungle: true
    BigJungle: true
    Oak: true
    Spruce: true
Leaf Decay:
  Fast Leaf Decay: true
Sapling Replant:
  Bottom Block has to be Broken First: true
  Time to Protect Sapling (Seconds): 0
  Replant When Tree Burns Down: true
  Block all breaking of Saplings: false
  Delay until Sapling is replanted (seconds) (minimum 1 second): 1
  Tree Types to Replant:
    Birch: true
    Jungle: true
    BigJungle: true
    Oak: true
    Spruce: true
Tools:
  Sapling Replant Require Tools: true
  Tree Destruction Require Tools: true
  Tools List:
  - DIAMOND_AXE
  - WOOD_AXE
  - GOLD_AXE
  - IRON_AXE
  - STONE_AXE
  - 5
  - 293
Worlds:
  Enable Per World: false
  Enabled Worlds:
  - world
  - world2
Modding:
  Custom Logs:
  - -1
  Custom Tree Blocks:
  - -1
  Custom Saplings:
  - -1
Config Help: dev.bukkit.org/server-mods/tree-assist/pages/config-walkthrough/