Main:
  Automatic Tree Destruction: true
  Use Permissions: false
  Sapling Replant: true
  Apply Full Tool Damage: true
  Ignore User Placed Blocks: false
  Use mcMMO if Available: true
  Destroy Only Blocks Above: false
  Auto Plant Dropped Saplings: false
Automatic Tree Destruction:
  Forced Removal: false
  Initial Delay (seconds): 10
  Delay (ticks): 0
  Tree Types:
    Birch: true
    Jungle: true
    BigJungle: true
    Oak: true
    Spruce: true
    Brown Shroom: true
    Red Shroom: true
  Cooldown (seconds): 0
Auto Plant Dropped Saplings:
  Chance (percent): 10
  Delay (seconds): 5
Leaf Decay:
  Fast Leaf Decay: true
Sapling Replant:
  Bottom Block has to be Broken First: true
  Time to Protect Sapling (Seconds): 0
  Replant When Tree Burns Down: true
  Block all breaking of Saplings: false
  Delay until Sapling is replanted (seconds) (minimum 1 second): 1
  Tree Types to Replant:
    Birch: true
    Jungle: true
    BigJungle: true
    Oak: true
    Spruce: true
    Brown Shroom: true
    Red Shroom: true
Tools:
  Sapling Replant Require Tools: true
  Tree Destruction Require Tools: true
  Tools List:
  - DIAMOND_AXE
  - WOOD_AXE
  - GOLD_AXE
  - IRON_AXE
  - STONE_AXE
  - 5
  - 293
  Drop Chance:
    DIAMOND_AXE: 100
    WOOD_AXE: 100
    GOLD_AXE: 100
    IRON_AXE: 100
    STONE_AXE: 100
Worlds:
  Enable Per World: false
  Enabled Worlds:
  - world
  - world2
Modding:
  Custom Logs:
  - -1
  Custom Tree Blocks:
  - -1
  Custom Saplings:
  - -1
Debug: none
Config Help: dev.bukkit.org/server-mods/tree-assist/pages/config-walkthrough/